name: aoc2018
version: 0.0.0.1
author: jonatan

dependencies:
  - base
  - containers
  - attoparsec
  - text

ghc-options:
  - -O2
  - -Wall

default-extensions:
  - OverloadedStrings

executables:
  3:
    main: main.hs
    source-dirs: '3'
  7:
    main: main.hs
    source-dirs: '7'
  1:
    main: main.hs
    source-dirs: '1'
