name: aoc2019
version: 0.0.0.1
author: jonatan

dependencies:

  - aeson
  - attoparsec
  - base
  - bytestring
  - conduit
  - containers
  - criterion
  - doctest
  - extra
  - hashable
  - hspec
  - lens
  - megaparsec
  - mtl
  - pretty-show
  - protolude
  - qm-interpolated-string
  - replace-attoparsec
  - safe
  - scientific
  - split
  - text
  - unordered-containers
  - vector

ghc-options:

- -O2
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

- -fno-warn-unused-do-bind

executables:
  main:
    main: Main.hs
    dependencies: aoc2019
    ghc-options:
      - -rtsopts

library:
  source-dirs:
    - src

tests:
  doctest:
    main: RunDocTests.hs
    source-dirs: test
    dependencies:
      - aoc2019
