name:                aoc2016
version:             0.1.0.0
github:              "githubuser/aoc2016"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

dependencies:

- aeson
- attoparsec
- base
- bytestring
- containers
- cryptonite
- cryptohash-md5
- base16-bytestring
- extra
- hashable
- megaparsec
- memory
- pretty-show
- protolude
- relude
- replace-attoparsec
- safe
- scientific
- split
- text
- unordered-containers

ghc-options:
  - -Wall

library:
  source-dirs: src
